#!/bin/bash
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")";
PROJECT_ROOT="$(cd "$SCRIPT_PATH/../../" && pwd)";
OUT_FILE="$PROJECT_ROOT/fbt.sh.bat";
UNIX_END="\n";
WIN_END="\r\n";
printf "echo >/dev/null # >nul & GOTO WINDOWS & rem ^$WIN_END" > "$OUT_FILE"
printf "# ***********************************************************$UNIX_END" >> "$OUT_FILE"
printf "# * NOTE: Generated by scripts/toolchain/generate-toolchain-download.sh$UNIX_END" >> "$OUT_FILE"
printf "# *       If you modify this file, use script or remove carriage returns (\\\r)\\\n$UNIX_END" >> "$OUT_FILE"
printf "# *       from the Unix part and leave them in Windows part. In summary:$UNIX_END" >> "$OUT_FILE"
printf "# *           New lines in Unix: \\\n\\\n$UNIX_END" >> "$OUT_FILE"
printf "# *           New lines in Windows: \\\r\\\n$UNIX_END" >> "$OUT_FILE"
printf "# ***********************************************************$UNIX_END" >> "$OUT_FILE"
printf "SCRIPT_PATH=\"\$(dirname -- \"\$(readlink -f -- \"\$0\")\")\";$UNIX_END" >> "$OUT_FILE"
printf "SCONS_DEFAULT_FLAGS=\"-Q --warn=target-not-built\"$UNIX_END" >> "$OUT_FILE"
printf "if [ ! -d \"\$SCRIPT_PATH/toolchain\" ]; then$UNIX_END" >> "$OUT_FILE"
printf "    scripts/toolchain/unix-toolchain-download.sh$UNIX_END" >> "$OUT_FILE"
printf "fi$UNIX_END" >> "$OUT_FILE"
printf "PATH=\"\$SCRIPT_PATH/toolchain/python/bin:\$PATH\"$UNIX_END" >> "$OUT_FILE"
printf "PATH=\"\$SCRIPT_PATH/toolchain/bin:\$PATH\"$UNIX_END" >> "$OUT_FILE"
printf "PATH=\"\$SCRIPT_PATH/toolchain/protobuf/bin:\$PATH\"$UNIX_END" >> "$OUT_FILE"
printf "python3 lib/scons/scripts/scons.py \$SCONS_DEFAULT_FLAGS \"\$@\"$UNIX_END" >> "$OUT_FILE"
printf "exit 0$UNIX_END" >> "$OUT_FILE"
printf ":WINDOWS$WIN_END" >> "$OUT_FILE"
printf "@echo off$WIN_END" >> "$OUT_FILE"
printf "cls$WIN_END" >> "$OUT_FILE"
printf "powershell -ExecutionPolicy Bypass -File scripts\\\toolchain\\\windows-toolchain-download.ps1$WIN_END" >> "$OUT_FILE"

chmod +x "$OUT_FILE"
