Import("env")

env.Append(
    CPPPATH=[
        "#/lib/storage_util",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("stream/buffered_file_stream.h"),
        File("stream/file_stream.h"),
        File("stream/stream_cache.h"),
        File("stream/stream.h"),
        File("stream/string_stream.h"),
        File("crc32_calc.h"),
        File("dir_walk.h"),
        File("md5_calc.h"),
        File("name_generator.h"),
        File("path.h"),
        File("saved_struct.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="storage_util")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
