ADD_SCENE(nfc, start, Start)
ADD_SCENE(nfc, file_select, FileSelect)
ADD_SCENE(nfc, read, Read)
ADD_SCENE(nfc, read_card_type, ReadCardType)
ADD_SCENE(nfc, nfca_read, NfcaRead)
ADD_SCENE(nfc, nfca_emulate, NfcaEmulate)
ADD_SCENE(nfc, nfca_read_success, NfcaReadSuccess)
ADD_SCENE(nfc, nfca_menu, NfcaMenu)
ADD_SCENE(nfc, extra_actions, ExtraActions)
ADD_SCENE(nfc, debug, Debug)
ADD_SCENE(nfc, retry_confirm, RetryConfirm)
ADD_SCENE(nfc, exit_confirm, ExitConfirm)
ADD_SCENE(nfc, mf_ultralight_read, MfUltralightRead)
ADD_SCENE(nfc, mf_ultralight_read_success, MfUltralightReadSuccess)
ADD_SCENE(nfc, mf_ultralight_menu, MfUltralightMenu)
ADD_SCENE(nfc, mf_ultralight_unlock_menu, MfUltralightUnlockMenu)
ADD_SCENE(nfc, mf_ultralight_unlock_warn, MfUltralightUnlockWarn)
ADD_SCENE(nfc, mf_ultralight_key_input, MfUltralightKeyInput)


ADD_SCENE(nfc, not_implemented, NotImplemented)