Import("env")

env.Append(
    CPPPATH=[
        "#/lib/cli",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("args.h"),
        File("cli_ansi.h"),
        File("cli_command.h"),
        File("cli_registry.h"),
        File("shell/cli_shell.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="cli")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
