ADD_SCENE(hex_viewer, startscreen, Startscreen)
ADD_SCENE(hex_viewer, menu, Menu)
ADD_SCENE(hex_viewer, scroll, Scroll)
ADD_SCENE(hex_viewer, info, Info)
ADD_SCENE(hex_viewer, open, Open)
ADD_SCENE(hex_viewer, settings, Settings)