ADD_SCENE(uhf, start, Start)
ADD_SCENE(uhf, read_tag, ReadTag)
ADD_SCENE(uhf, read_tag_success, ReadTagSuccess)
// ADD_SCENE(uhf, card_menu, CardMenu)
// ADD_SCENE(uhf, save_name, SaveName)
// ADD_SCENE(uhf, save_success, SaveSuccess)
// ADD_SCENE(uhf, saved_menu, SavedMenu)
// ADD_SCENE(uhf, file_select, FileSelect)
// ADD_SCENE(uhf, device_info, DeviceInfo)
// ADD_SCENE(uhf, delete, Delete)
// ADD_SCENE(uhf, delete_success, DeleteSuccess)
// ADD_SCENE(uhf, write_card, WriteCard)
// ADD_SCENE(uhf, write_card_success, WriteCardSuccess)
// ADD_SCENE(uhf, read_factory_success, ReadFactorySuccess)
// ADD_SCENE(uhf, write_key, WriteKey)
// ADD_SCENE(uhf, key_menu, KeyMenu)
