# Example / test for handling 'map' type using the backwards compatibility
# in protobuf specification:
# https://developers.google.com/protocol-buffers/docs/proto3#maps

Import('env')

env.NanopbProto(['map', 'map.options'])

enc = env.Program(['encode_map.c',
                'map.pb.c',
                '$COMMON/pb_encode.o',
                '$COMMON/pb_common.o'])

dec = env.Program(['decode_map.c',
                'map.pb.c',
                '$COMMON/pb_decode.o',
                '$COMMON/pb_common.o'])

env.RunTest("message.pb", enc)
env.RunTest("message.txt", [dec, 'message.pb'])

