#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)";
. $SCRIPT_PATH/scripts/toolchain/fbtenv.sh;

if [ ! -d "${FBT_ROOT:-.}/.git" ]; then
    echo "\".git\" directory not found, please clone repo via \"git clone --recursive\"";
    exit 1;
fi

git submodule update --init;

SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built";
python3 "$SCRIPT_PATH/lib/scons/scripts/scons.py" $SCONS_DEFAULT_FLAGS "$@"
