#!/bin/bash

set -e

if [[ -d .git ]]; then
	echo "Prepairing git submodules"
	git submodule init
	git submodule update
fi

SCRIPTDIR="$( dirname -- "$0"; )";
SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built"
python3 ${SCRIPTDIR}/lib/scons/scripts/scons.py ${SCONS_DEFAULT_FLAGS} "$@"
