#include <furi.h>
#include <furi_hal.h>

/* generated by fbt from .png files in images folder */
#include <gas_sensor_icons.h>

#include "gas_sensor_i.h"
#include "helpers/bme680.h"

#define TAG "gas_sensor_app"

int32_t gas_sensor_app(void* p) {
    UNUSED(p);

    GasSensorApp* gas_app = gas_sensor_app_alloc();
    view_dispatcher_run(gas_app->view_dispatcher);

    gas_sensor_app_free(gas_app);
    return 0;
}
