#include <furi.h>

#include "minesweeper.h"
#include "minesweeper_i.h"

/* generated by fbt from .png files in images folder */
#include <minesweeper_icons.h>

static void (*const minesweeper_scene_on_enter_handlers[])(void*) = {
    minesweeper_scenes_startup_scene_on_enter,
    minesweeper_scenes_game_on_enter,
    minesweeper_scenes_menu_on_enter,
};

static bool (*const minesweeper_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    minesweeper_scenes_startup_scene_on_event,
    minesweeper_scenes_game_on_event,
    minesweeper_scenes_menu_on_event,
};

static void (*const minesweeper_scene_on_exit_handlers[])(void*) = {
    minesweeper_scenes_startup_scene_on_exit,
    minesweeper_scenes_game_on_exit,
    minesweeper_scenes_menu_on_exit,
};

static const SceneManagerHandlers minesweeper_scene_manager_handlers = {
    .on_enter_handlers = minesweeper_scene_on_enter_handlers,
    .on_event_handlers = minesweeper_scene_on_event_handlers,
    .on_exit_handlers = minesweeper_scene_on_exit_handlers,
    .scene_num = MineSweeperSceneCount, 
};

static bool minesweeper_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

static bool minesweeper_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

static App* app_alloc() { 
    App* app = (App*)malloc(sizeof(App));
    furi_assert(app);

    app->app_state = (AppState*)malloc(sizeof(AppState));

    app->scene_manager = scene_manager_alloc(&minesweeper_scene_manager_handlers, app);
    furi_assert(app->scene_manager);

    app->view_dispatcher = view_dispatcher_alloc();
    furi_assert(app->view_dispatcher);

    view_dispatcher_enable_queue(app->view_dispatcher);
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, minesweeper_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, minesweeper_back_event_callback);

    app->popup_view = NULL;
    app->popup = popup_alloc();
    view_dispatcher_add_view(app->view_dispatcher, MineSweeperPopupView, popup_get_view(app->popup));

    app->empty_screen_view = NULL;
    app->empty_screen = empty_screen_alloc();
    view_dispatcher_add_view(app->view_dispatcher, MineSweeperEmptyScreenView, empty_screen_get_view(app->empty_screen));

    app->loading = loading_alloc();
    view_dispatcher_add_view(app->view_dispatcher, MineSweeperLoadingView, loading_get_view(app->loading));

    app->menu = dialog_ex_alloc();
    view_dispatcher_add_view(app->view_dispatcher, MineSweeperMenuView, dialog_ex_get_view(app->menu));

    return app;

}

static void app_free(App* app) {
    furi_assert(app);
    
    for (MineSweeperView minesweeper_view = MineSweeperPopupView; minesweeper_view < MineSweeperPopupCount; minesweeper_view++) {
        view_dispatcher_remove_view(app->view_dispatcher, minesweeper_view);
    }

    scene_manager_free(app->scene_manager);

    view_dispatcher_free(app->view_dispatcher);

    popup_free(app->popup);
    empty_screen_free(app->empty_screen);
    loading_free(app->loading);
    dialog_ex_free(app->menu);

    free(app->app_state);
    free(app);

}

int32_t minesweeper_app(void* p) {
    UNUSED(p);

    App* app = app_alloc();

    Gui* gui = furi_record_open(RECORD_GUI);

    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    
    scene_manager_next_scene(app->scene_manager, MineSweeperStartupScene);

    view_dispatcher_run(app->view_dispatcher);

    app_free(app);

    return 0;
}
