#include <named_list.h>
#include <pokemon_data.h>

const NamedList move_list[] = {
    {"No Move", 0x00, (GEN_I | GEN_II)},
    {"Absorb", 0x47, (GEN_I | GEN_II)},
    {"Acid", 0x33, (GEN_I | GEN_II)},
    {"Acid Armor", 0x97, (GEN_I | GEN_II)},
    {"Aeroblast", 0xB1, GEN_II},
    {"Agility", 0x61, (GEN_I | GEN_II)},
    {"Amnesia", 0x85, (GEN_I | GEN_II)},
    {"Ancient Power", 0xF6, GEN_II},
    {"Attract", 0xD5, GEN_II},
    {"Aurora Beam", 0x3E, (GEN_I | GEN_II)},
    {"Barrage", 0x8C, (GEN_I | GEN_II)},
    {"Barrier", 0x70, (GEN_I | GEN_II)},
    {"Baton Pass", 0xE2, GEN_II},
    {"Beat Up", 0xFB, GEN_II},
    {"Belly Drum", 0xBB, GEN_II},
    {"Bide", 0x75, (GEN_I | GEN_II)},
    {"Bind", 0x14, (GEN_I | GEN_II)},
    {"Bite", 0x2C, (GEN_I | GEN_II)},
    {"Blizzard", 0x3B, (GEN_I | GEN_II)},
    {"Body Slam", 0x22, (GEN_I | GEN_II)},
    {"Bone Club", 0x7D, (GEN_I | GEN_II)},
    {"Bone Rush", 0xC6, GEN_II},
    {"Boomerang", 0x9B, (GEN_I | GEN_II)},
    {"Bubble", 0x91, (GEN_I | GEN_II)},
    {"Bubblebeam", 0x3D, (GEN_I | GEN_II)},
    {"Charm", 0xCC, GEN_II},
    {"Clamp", 0x80, (GEN_I | GEN_II)},
    {"Comet Punch", 0x04, (GEN_I | GEN_II)},
    {"Confuse Ray", 0x6D, (GEN_I | GEN_II)},
    {"Confusion", 0x5D, (GEN_I | GEN_II)},
    {"Constrict", 0x84, (GEN_I | GEN_II)},
    {"Conversion", 0xA0, (GEN_I | GEN_II)},
    {"Conversion 2", 0xB0, GEN_II},
    {"Cotton Spore", 0xB2, GEN_II},
    {"Counter", 0x44, (GEN_I | GEN_II)},
    {"Crabhammer", 0x98, (GEN_I | GEN_II)},
    {"Cross Chop", 0xEE, GEN_II},
    {"Crunch", 0xF2, GEN_II},
    {"Curse", 0xAE, GEN_II},
    {"Cut", 0x0F, (GEN_I | GEN_II)},
    {"Defense Curl", 0x6F, (GEN_I | GEN_II)},
    {"Destiny Bond", 0xC2, GEN_II},
    {"Detect", 0xC5, GEN_II},
    {"Dig", 0x5B, (GEN_I | GEN_II)},
    {"Disable", 0x32, (GEN_I | GEN_II)},
    {"Dizzy Punch", 0x92, (GEN_I | GEN_II)},
    {"Double-Edge", 0x26, (GEN_I | GEN_II)},
    {"Double Kick", 0x18, (GEN_I | GEN_II)},
    {"Doubleslap", 0x03, (GEN_I | GEN_II)},
    {"Double Team", 0x68, (GEN_I | GEN_II)},
    {"Dragon Breath", 0xE1, GEN_II},
    {"Dragon Rage", 0x52, (GEN_I | GEN_II)},
    {"Dream Eater", 0x8A, (GEN_I | GEN_II)},
    {"Drill Peck", 0x41, (GEN_I | GEN_II)},
    {"Dynamic Punch", 0xDF, GEN_II},
    {"Earthquake", 0x59, (GEN_I | GEN_II)},
    {"Egg Bomb", 0x79, (GEN_I | GEN_II)},
    {"Ember", 0x34, (GEN_I | GEN_II)},
    {"Encore", 0xE3, GEN_II},
    {"Endure", 0xCB, GEN_II},
    {"Explosion", 0x99, (GEN_I | GEN_II)},
    {"Extreme Speed", 0xF5, GEN_II},
    {"False Swipe", 0xCE, GEN_II},
    {"Feint Attack", 0xB9, GEN_II},
    {"Fire Blast", 0x7E, (GEN_I | GEN_II)},
    {"Fire Punch", 0x07, (GEN_I | GEN_II)},
    {"Fire Spin", 0x53, (GEN_I | GEN_II)},
    {"Fissure", 0x5A, (GEN_I | GEN_II)},
    {"Flail", 0xAF, GEN_II},
    {"Flamethrower", 0x35, (GEN_I | GEN_II)},
    {"Flame Wheel", 0xAC, GEN_II},
    {"Flash", 0x94, (GEN_I | GEN_II)},
    {"Fly", 0x13, (GEN_I | GEN_II)},
    {"Focus Energy", 0x74, (GEN_I | GEN_II)},
    {"Foresight", 0xC1, GEN_II},
    {"Frustration", 0xDA, GEN_II},
    {"Fury Attack", 0x1F, (GEN_I | GEN_II)},
    {"Fury Cutter", 0xD2, GEN_II},
    {"Fury Swipes", 0x9A, (GEN_I | GEN_II)},
    {"Future Sight", 0xF8, GEN_II},
    {"Giga Drain", 0xCA, GEN_II},
    {"Glare", 0x89, (GEN_I | GEN_II)},
    {"Growl", 0x2D, (GEN_I | GEN_II)},
    {"Growth", 0x4A, (GEN_I | GEN_II)},
    {"Guillotine", 0x0C, (GEN_I | GEN_II)},
    {"Gust", 0x10, (GEN_I | GEN_II)},
    {"Harden", 0x6A, (GEN_I | GEN_II)},
    {"Haze", 0x72, (GEN_I | GEN_II)},
    {"Headbutt", 0x1D, (GEN_I | GEN_II)},
    {"Heal Bell", 0xD7, GEN_II},
    {"Hidden Power", 0xED, GEN_II},
    {"Hi Jump Kick", 0x88, (GEN_I | GEN_II)},
    {"Horn Attack", 0x1E, (GEN_I | GEN_II)},
    {"Horn Drill", 0x20, (GEN_I | GEN_II)},
    {"Hydro Pump", 0x38, (GEN_I | GEN_II)},
    {"Hyper Beam", 0x3F, (GEN_I | GEN_II)},
    {"Hyper Fang", 0x9E, (GEN_I | GEN_II)},
    {"Hypnosis", 0x5F, (GEN_I | GEN_II)},
    {"Ice Beam", 0x3A, (GEN_I | GEN_II)},
    {"Ice Punch", 0x08, (GEN_I | GEN_II)},
    {"Icy Wind", 0xC4, GEN_II},
    {"Iron Tail", 0xE7, GEN_II},
    {"Jump Kick", 0x1A, (GEN_I | GEN_II)},
    {"Karate Chop", 0x02, (GEN_I | GEN_II)},
    {"Kinesis", 0x86, (GEN_I | GEN_II)},
    {"Leech Life", 0x8D, (GEN_I | GEN_II)},
    {"Leech Seed", 0x49, (GEN_I | GEN_II)},
    {"Leer", 0x2B, (GEN_I | GEN_II)},
    {"Lick", 0x7A, (GEN_I | GEN_II)},
    {"Light Screen", 0x71, (GEN_I | GEN_II)},
    {"Lock-On", 0xC7, GEN_II},
    {"Lovely Kiss", 0x8E, (GEN_I | GEN_II)},
    {"Low Kick", 0x43, (GEN_I | GEN_II)},
    {"Mach Punch", 0xB7, GEN_II},
    {"Magnitude", 0xDE, GEN_II},
    {"Mean Look", 0xD4, GEN_II},
    {"Meditate", 0x60, (GEN_I | GEN_II)},
    {"Mega Drain", 0x48, (GEN_I | GEN_II)},
    {"Megahorn", 0xE0, GEN_II},
    {"Mega Kick", 0x19, (GEN_I | GEN_II)},
    {"Mega Punch", 0x05, (GEN_I | GEN_II)},
    {"Metal Claw", 0xE8, GEN_II},
    {"Metronome", 0x76, (GEN_I | GEN_II)},
    {"Milk Drink", 0xD0, GEN_II},
    {"Mimic", 0x66, (GEN_I | GEN_II)},
    {"Mind Reader", 0xAA, GEN_II},
    {"Minimize", 0x6B, (GEN_I | GEN_II)},
    {"Mirror Coat", 0xF3, GEN_II},
    {"Mirror Move", 0x77, (GEN_I | GEN_II)},
    {"Mist", 0x36, (GEN_I | GEN_II)},
    {"Moonlight", 0xEC, GEN_II},
    {"Morning Sun", 0xEA, GEN_II},
    {"Mud-Slap", 0xBD, GEN_II},
    {"Nightmare", 0xAB, GEN_II},
    {"Night Shade", 0x65, (GEN_I | GEN_II)},
    {"Octazooka", 0xBE, GEN_II},
    {"Outrage", 0xC8, GEN_II},
    {"Pain Split", 0xDC, GEN_II},
    {"Pay Day", 0x06, (GEN_I | GEN_II)},
    {"Peck", 0x40, (GEN_I | GEN_II)},
    {"Perish Song", 0xC3, GEN_II},
    {"Petal Dance", 0x50, (GEN_I | GEN_II)},
    {"Pin Missile", 0x2A, (GEN_I | GEN_II)},
    {"Poison Gas", 0x8B, (GEN_I | GEN_II)},
    {"Poisonpowder", 0x4D, (GEN_I | GEN_II)},
    {"Poison Sting", 0x28, (GEN_I | GEN_II)},
    {"Pound", 0x01, (GEN_I | GEN_II)},
    {"Powder Snow", 0xB5, GEN_II},
    {"Present", 0xD9, GEN_II},
    {"Protect", 0xB6, GEN_II},
    {"Psybeam", 0x3C, (GEN_I | GEN_II)},
    {"Psychic", 0x5E, (GEN_I | GEN_II)},
    {"Psych Up", 0xF4, GEN_II},
    {"Psywave", 0x95, (GEN_I | GEN_II)},
    {"Pursuit", 0xE4, GEN_II},
    {"Quick Attack", 0x62, (GEN_I | GEN_II)},
    {"Rage", 0x63, (GEN_I | GEN_II)},
    {"Rain Dance", 0xF0, GEN_II},
    {"Rapid Spin", 0xE5, GEN_II},
    {"Razor Leaf", 0x4B, (GEN_I | GEN_II)},
    {"Razor Wind", 0x0D, (GEN_I | GEN_II)},
    {"Recover", 0x69, (GEN_I | GEN_II)},
    {"Reflect", 0x73, (GEN_I | GEN_II)},
    {"Rest", 0x9C, (GEN_I | GEN_II)},
    {"Return", 0xD8, GEN_II},
    {"Reversal", 0xB3, GEN_II},
    {"Roar", 0x2E, (GEN_I | GEN_II)},
    {"Rock Slide", 0x9D, (GEN_I | GEN_II)},
    {"Rock Smash", 0xF9, GEN_II},
    {"Rock Throw", 0x58, (GEN_I | GEN_II)},
    {"Rolling Kick", 0x1B, (GEN_I | GEN_II)},
    {"Rollout", 0xCD, GEN_II},
    {"Sacred Fire", 0xDD, GEN_II},
    {"Safeguard", 0xDB, GEN_II},
    {"Sand Attack", 0x1C, (GEN_I | GEN_II)},
    {"Sandstorm", 0xC9, GEN_II},
    {"Scary Face", 0xB8, GEN_II},
    {"Scratch", 0x0A, (GEN_I | GEN_II)},
    {"Screech", 0x67, (GEN_I | GEN_II)},
    {"Seismic Toss", 0x45, (GEN_I | GEN_II)},
    {"Selfdestruct", 0x78, (GEN_I | GEN_II)},
    {"Shadow Ball", 0xF7, GEN_II},
    {"Sharpen", 0x9F, (GEN_I | GEN_II)},
    {"Sing", 0x2F, (GEN_I | GEN_II)},
    {"Sketch", 0xA6, GEN_II},
    {"Skull Bash", 0x82, (GEN_I | GEN_II)},
    {"Sky Attack", 0x8F, (GEN_I | GEN_II)},
    {"Slam", 0x15, (GEN_I | GEN_II)},
    {"Slash", 0xA3, (GEN_I | GEN_II)},
    {"Sleep Powder", 0x4F, (GEN_I | GEN_II)},
    {"Sleep Talk", 0xD6, GEN_II},
    {"Sludge", 0x7C, (GEN_I | GEN_II)},
    {"Sludge Bomb", 0xBC, GEN_II},
    {"Smog", 0x7B, (GEN_I | GEN_II)},
    {"Smokescreen", 0x6C, (GEN_I | GEN_II)},
    {"Snore", 0xAD, GEN_II},
    {"Softboiled", 0x87, (GEN_I | GEN_II)},
    {"Solar Beam", 0x4C, (GEN_I | GEN_II)},
    {"Sonicboom", 0x31, (GEN_I | GEN_II)},
    {"Spark", 0xD1, GEN_II},
    {"Spider Web", 0xA9, GEN_II},
    {"Spike Cannon", 0x83, (GEN_I | GEN_II)},
    {"Spikes", 0xBF, GEN_II},
    {"Spite", 0xB4, GEN_II},
    {"Splash", 0x96, (GEN_I | GEN_II)},
    {"Spore", 0x93, (GEN_I | GEN_II)},
    {"Steel Wing", 0xD3, GEN_II},
    {"Stomp", 0x17, (GEN_I | GEN_II)},
    {"Strength", 0x46, (GEN_I | GEN_II)},
    {"String Shot", 0x51, (GEN_I | GEN_II)},
    {"Struggle", 0xA5, (GEN_I | GEN_II)},
    {"Stun Spore", 0x4E, (GEN_I | GEN_II)},
    {"Submission", 0x42, (GEN_I | GEN_II)},
    {"Substitute", 0xA4, (GEN_I | GEN_II)},
    {"Sunny Day", 0xF1, GEN_II},
    {"Super Fang", 0xA2, (GEN_I | GEN_II)},
    {"Supersonic", 0x30, (GEN_I | GEN_II)},
    {"Surf", 0x39, (GEN_I | GEN_II)},
    {"Swagger", 0xCF, GEN_II},
    {"Sweet Kiss", 0xBA, GEN_II},
    {"Sweet Scent", 0xE6, GEN_II},
    {"Swift", 0x81, (GEN_I | GEN_II)},
    {"Swords Dance", 0x0E, (GEN_I | GEN_II)},
    {"Synthesis", 0xEB, GEN_II},
    {"Tackle", 0x21, (GEN_I | GEN_II)},
    {"Tail Whip", 0x27, (GEN_I | GEN_II)},
    {"Take Down", 0x24, (GEN_I | GEN_II)},
    {"Teleport", 0x64, (GEN_I | GEN_II)},
    {"Thief", 0xA8, GEN_II},
    {"Thrash", 0x25, (GEN_I | GEN_II)},
    {"Thunder", 0x57, (GEN_I | GEN_II)},
    {"Thunderbolt", 0x55, (GEN_I | GEN_II)},
    {"Thunderpunch", 0x09, (GEN_I | GEN_II)},
    {"Thundershock", 0x54, (GEN_I | GEN_II)},
    {"Thunder Wave", 0x56, (GEN_I | GEN_II)},
    {"Toxic", 0x5C, (GEN_I | GEN_II)},
    {"Transform", 0x90, (GEN_I | GEN_II)},
    {"Tri Attack", 0xA1, (GEN_I | GEN_II)},
    {"Triple Kick", 0xA7, GEN_II},
    {"Twineedle", 0x29, (GEN_I | GEN_II)},
    {"Twister", 0xEF, GEN_II},
    {"Vicegrip", 0x0B, (GEN_I | GEN_II)},
    {"Vine Whip", 0x16, (GEN_I | GEN_II)},
    {"Vital Throw", 0xE9, GEN_II},
    {"Waterfall", 0x7F, (GEN_I | GEN_II)},
    {"Water Gun", 0x37, (GEN_I | GEN_II)},
    {"Whirlpool", 0xFA, GEN_II},
    {"Whirlwind", 0x12, (GEN_I | GEN_II)},
    {"Wing Attack", 0x11, (GEN_I | GEN_II)},
    {"Withdraw", 0x6E, (GEN_I | GEN_II)},
    {"Wrap", 0x23, (GEN_I | GEN_II)},
    {"Zap Cannon", 0xC0, GEN_II},
    {},
};
