#include "flipper.h"
#include "app_state.h"
#include "scenes/scenes.h"
#include "scenes/scene_items.h"

/* generated by fbt from .png files in images folder */
#include <quac_icons.h>

int32_t quac_app(void* p) {
    UNUSED(p);
    FURI_LOG_I(TAG, "QUAC QUAC!!");

    App* app = app_alloc();
    // initialize any app state

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, SR_Scene_Items);
    view_dispatcher_run(app->view_dispatcher);

    furi_record_close(RECORD_GUI);
    app_free(app);
    return 0;
}
