#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <tone_gen_icons.h>

int32_t tone_gen_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm tone_gen!");

    return 0;
}
