Import("env")

env.Append(
    CPPPATH=[
        "#/lib/debug",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("profiler.h"),
        File("pretty_format.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="debug")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
