#!/bin/bash 
#------------------------
SERIAL_ID=ttyACM0
APPID=kcline
FIRMWARE_DIR=~/Programming/Flipper/f0ReleaseFirmware
SOURCE_DIR=~/Programming/Flipper/applications_user/$APPID/
#------------------------
# Reboot the device in case another application is running.
clear
echo "Rebooting Flipper..."
# Send command directly to the Flipper over serial connection
echo -en 'power reboot\r\n' >> /dev/$SERIAL_ID
set -x
cp -r $SOURCE_DIR $FIRMWARE_DIR/applications_user/
cd $FIRMWARE_DIR
./fbt -c fap_$APPID
./fbt fap_$APPID
./fbt launch_app APPSRC=$APPID
set +x
echo "For Update/Release:"
echo "1. Git pull/merge the forked flipper-application-catalog so your version is current"
echo "2. Create a new branch for the new app version/release HappyAmos/$APPI\_1.0 in forked flipper-application-catalog"
echo "3. Add manifest and directory to flipper-application-catalog if they don't exist already"
echo "   ~/Programming/Flipper/flipper-application-catalog/applications/APP_CATEGORY/$APPID/manifest.yml"
echo "4. Update the commit_sha in the manifest for release, as well as the version info in application.fam"
echo "5. Run the manifest validator"
echo "6. Fill out pull request"
echo "7. Done."
