# Regression test for #395:
# Unexpected empty submessage in proto3 mode

Import("env")

env.NanopbProto(["test.proto", "test.options"])
testprog = env.Program(["test.c",
                 "test.pb.c",
                 "$COMMON/pb_encode.o",
                 "$COMMON/pb_decode.o",
                 "$COMMON/pb_common.o"])

env.RunTest(testprog)

