Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/infrared/encoder_decoder",
        "#/lib/infrared/worker",
    ],
)


libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("infrared", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
