Import("env")

env.Append(
    CPPPATH=[
        "#/lib/signal_common",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("protocols/protocol_dict.h"),
        File("protocols/protocol.h"),
        File("pulse_protocols/pulse_glue.h"),
        File("level_duration.h"),
        File("manchester_decoder.h"),
        File("manchester_encoder.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="signal_common")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
