/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_CardDetails_H_
#define	_CardDetails_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Protocol.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CardDetails */
typedef struct CardDetails {
	Protocol_t	 protocol;
	OCTET_STRING_t	 csn;
	OCTET_STRING_t	*atqa	/* OPTIONAL */;
	OCTET_STRING_t	*sak	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CardDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CardDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_CardDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_CardDetails_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CardDetails_H_ */
#include <asn_internal.h>
