/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_FrameProtocol_H_
#define	_FrameProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FrameProtocol {
	FrameProtocol_nfc	= 2,
	FrameProtocol_iclass	= 4
} e_FrameProtocol;

/* FrameProtocol */
typedef long	 FrameProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FrameProtocol;
asn_struct_free_f FrameProtocol_free;
asn_struct_print_f FrameProtocol_print;
asn_constr_check_f FrameProtocol_constraint;
ber_type_decoder_f FrameProtocol_decode_ber;
der_type_encoder_f FrameProtocol_encode_der;
xer_type_decoder_f FrameProtocol_decode_xer;
xer_type_encoder_f FrameProtocol_encode_xer;
oer_type_decoder_f FrameProtocol_decode_oer;
oer_type_encoder_f FrameProtocol_encode_oer;
per_type_decoder_f FrameProtocol_decode_uper;
per_type_encoder_f FrameProtocol_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FrameProtocol_H_ */
#include <asn_internal.h>
