/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#include "NFCResponse.h"

static asn_oer_constraints_t asn_OER_type_NFCResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_NFCResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_NFCResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NFCResponse, choice.nfcRx),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NFCRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nfcRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NFCResponse, choice.nfcAck),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nfcAck"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NFCResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nfcRx */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* nfcAck */
};
asn_CHOICE_specifics_t asn_SPC_NFCResponse_specs_1 = {
	sizeof(struct NFCResponse),
	offsetof(struct NFCResponse, _asn_ctx),
	offsetof(struct NFCResponse, present),
	sizeof(((struct NFCResponse *)0)->present),
	asn_MAP_NFCResponse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NFCResponse = {
	"NFCResponse",
	"NFCResponse",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_NFCResponse_constr_1, &asn_PER_type_NFCResponse_constr_1, CHOICE_constraint },
	asn_MBR_NFCResponse_1,
	2,	/* Elements count */
	&asn_SPC_NFCResponse_specs_1	/* Additional specs */
};

