/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_RfStatus_H_
#define	_RfStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RfStatus */
typedef OCTET_STRING_t	 RfStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RfStatus;
asn_struct_free_f RfStatus_free;
asn_struct_print_f RfStatus_print;
asn_constr_check_f RfStatus_constraint;
ber_type_decoder_f RfStatus_decode_ber;
der_type_encoder_f RfStatus_encode_der;
xer_type_decoder_f RfStatus_decode_xer;
xer_type_encoder_f RfStatus_encode_xer;
oer_type_decoder_f RfStatus_decode_oer;
oer_type_encoder_f RfStatus_encode_oer;
per_type_decoder_f RfStatus_decode_uper;
per_type_encoder_f RfStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RfStatus_H_ */
#include <asn_internal.h>
