/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_Version_H_
#define	_Version_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Version */
typedef struct Version {
	OCTET_STRING_t	 v;
	OCTET_STRING_t	 f;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Version_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Version;

#ifdef __cplusplus
}
#endif

#endif	/* _Version_H_ */
#include <asn_internal.h>
