Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/flipper_format",
    ],
    CPPDEFINES=[],
)


libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c", ".")

lib = libenv.StaticLibrary("flipperformat", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
