Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/flipper_format",
    ],
)


libenv = env.Clone()
libenv.MergeFlags(lib_flags)

if libenv["RAM_EXEC"]:
    libenv.Append(
        CPPDEFINES=[
            "FLIPPER_STREAM_LITE",
        ],
    )


sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("flipperformat", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
