/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_NFCRx_H_
#define	_NFCRx_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "RfStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NFCRx */
typedef struct NFCRx {
	OCTET_STRING_t	*data	/* OPTIONAL */;
	RfStatus_t	 rfStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NFCRx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NFCRx;
extern asn_SEQUENCE_specifics_t asn_SPC_NFCRx_specs_1;
extern asn_TYPE_member_t asn_MBR_NFCRx_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NFCRx_H_ */
#include <asn_internal.h>
