/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_NFCSend_H_
#define	_NFCSend_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "Protocol.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NFCSend */
typedef struct NFCSend {
	OCTET_STRING_t	 data;
	Protocol_t	 protocol;
	long	 timeOut;
	OCTET_STRING_t	*format	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NFCSend_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NFCSend;
extern asn_SEQUENCE_specifics_t asn_SPC_NFCSend_specs_1;
extern asn_TYPE_member_t asn_MBR_NFCSend_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NFCSend_H_ */
#include <asn_internal.h>
