Import("env")

env.Append(
    CPPPATH=[
        "#/lib/TOTP-MCU",
    ],
    SDK_HEADERS=[
        File("#/lib/TOTP-MCU/TOTP.h"),
    ],
)


libenv = env.Clone(FW_LIB_NAME="TOTPMCU")
libenv.ApplyLibFlags()

sources = Glob("*.c", source=True)

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
