Import("env")

env.Append(
    CPPPATH=[
        "#/lib/flipper_application",
    ],
    SDK_HEADERS=[
        File("flipper_application.h"),
        File("application_library/application_lib_manager.h"),
        File("application_library/composite_resolver.h"),
        File("api_hashtable/api_hashtable.h"),
        File("api_hashtable/compilesort.hpp"),
    ],
)


libenv = env.Clone(FW_LIB_NAME="flipper_application")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")
sources.append(File("api_hashtable/api_hashtable.cpp"))

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
