# Test stack usage

Import("env")

env.NanopbProto(["stackusage", "stackusage.options"])
test = env.Program(["stackusage.c", "stackusage.pb.c", "$COMMON/pb_encode.o", "$COMMON/pb_decode.o", "$COMMON/pb_common.o"])
env.RunTest(test)
