Import("env")

env.Append(
    LINT_SOURCES=["core"],
    SDK_HEADERS=[File("#/core/intrinsic_export.h")],
)


libenv = env.Clone(FW_LIB_NAME="core")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
