Import("env", "lib_flags")

libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c")

lib = libenv.Library("core", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
