#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define NFC_LSB_ATQA_FORMAT_VERSION (2)
#define NFC_MINIMUM_SUPPORTED_FORMAT_VERSION NFC_LSB_ATQA_FORMAT_VERSION
#define NFC_UNIFIED_FORMAT_VERSION (4)
#define NFC_CURRENT_FORMAT_VERSION NFC_UNIFIED_FORMAT_VERSION

#ifdef __cplusplus
}
#endif
