Import("env")

env.Append(
    CPPPATH=[
        "#/lib/nfc",
    ],
    SDK_HEADERS=[
        File("protocols/mf_classic/mf_classic.h"),
        File("protocols/mf_classic/mf_classic_poller.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="nfc")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
