#pragma once

#include "../lib/driver/avr_isp_prog_cmd.h"

#define AVR_ISP_RW_GET_SYNC STK_GET_SYNC,CRC_EOP
#define AVR_ISP_RW_ENTER_PROGMODE STK_ENTER_PROGMODE,CRC_EOP
#define AVR_ISP_RW_READ_SIGN STK_READ_SIGN,CRC_EOP
#define AVR_ISP_RW_LEAVE_PROGMODE STK_LEAVE_PROGMODE,CRC_EOP
