#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <resistors_icons.h>

int32_t resistors_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm resistors!");

    return 0;
}
