Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/microtar/src",
        "#/lib/toolbox",
    ],
    CPPDEFINES=[],
)


libenv = env.Clone()
libenv.MergeFlags(lib_flags)
# TODO: consider adding optimization flags for microtar here

sources = libenv.GlobRecursive("*.c", ".")
sources += libenv.GlobRecursive("*.c", "../microtar/src")

lib = libenv.StaticLibrary("toolbox", sources)
libenv.Install("#/${BUILD_DIR}/lib", lib)
Return("lib")
