Import("env")

env.Append(
    CPPPATH=[
        "#/lib/compress",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("compress.h"),
        File("tar/tar_archive.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="compress")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
