# Regression test for #544:
# Decoding whole submessage in submessage callback causes "missing required field"

Import("env")
env.NanopbProto("submsg_callback")

test = env.Program(["submsg_callback.c", "submsg_callback.pb.c", "$COMMON/pb_encode.o", "$COMMON/pb_decode.o", "$COMMON/pb_common.o"])
env.RunTest(test)
