/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "main.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Nfc_Empty, Nfc_Empty, AUTO)


PB_BIND(Nfc_Main, Nfc_Main, AUTO)




