/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_NFC_MAIN_PB_H_INCLUDED
#define PB_NFC_MAIN_PB_H_INCLUDED
#include <pb.h>
#include "nfca.pb.h"
#include "mf_ultralight.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Nfc_CommandStatus {
    Nfc_CommandStatus_OK = 0,
    Nfc_CommandStatus_ERROR = 1, /* *< Unknown error */
    Nfc_CommandStatus_ERROR_NOT_IMPLEMENTED = 3, /* *< Command succesfully decoded, but not
implemented (deprecated or not yet implemented) */
    Nfc_CommandStatus_ERROR_BUSY = 4 /* *< Somebody took global lock, so not all commands are available */
} Nfc_CommandStatus;

/* Struct definitions */
typedef struct _Nfc_Empty {
    char dummy_field;
} Nfc_Empty;

typedef struct _Nfc_Main {
    Nfc_CommandStatus command_status;
    pb_callback_t cb_content;
    pb_size_t which_content;
    union {
        Nfc_Empty empty;
        PB_Nfca_ReadRequest nfca_read_req;
        PB_Nfca_ReadResponse nfca_read_resp;
        PB_Nfca_EmulateStartRequest nfca_emulate_start_req;
        PB_Nfca_EmulateStartResponse nfca_emulate_start_resp;
        PB_Nfca_EmulateStopRequest nfca_emulate_stop_req;
        PB_Nfca_EmulateStopResponse nfca_emulate_stop_resp;
        PB_MfUltralight_ReadPageRequest mf_ultralight_read_page_req;
        PB_MfUltralight_ReadPageResponse mf_ultralight_read_page_resp;
        PB_MfUltralight_ReadVersionRequest mf_ultralight_read_version_req;
        PB_MfUltralight_ReadVersionResponse mf_ultralight_read_version_resp;
        PB_MfUltralight_WritePageRequest mf_ultralight_write_page_req;
        PB_MfUltralight_WritePageResponse mf_ultralight_write_page_resp;
        PB_MfUltralight_ReadSignatureRequest mf_ultralight_read_signature_req;
        PB_MfUltralight_ReadSignatureResponse mf_ultralight_read_signature_resp;
        PB_MfUltralight_ReadCounterRequest mf_ultralight_read_counter_req;
        PB_MfUltralight_ReadCounterResponse mf_ultralight_read_counter_resp;
        PB_MfUltralight_ReadTearingFlagRequest mf_ultralight_read_tearing_flag_req;
        PB_MfUltralight_ReadTearingFlagResponse mf_ultralight_read_tearing_flag_resp;
        PB_MfUltralight_EmulateStartRequest mf_ultralight_emulate_start_req;
        PB_MfUltralight_EmulateStartResponse mf_ultralight_emulate_start_resp;
        PB_MfUltralight_EmulationStopRequest mf_ultralight_emulate_stop_req;
        PB_MfUltralight_EmulationStopResponse mf_ultralight_emulate_stop_resp;
    } content;
} Nfc_Main;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Nfc_CommandStatus_MIN Nfc_CommandStatus_OK
#define _Nfc_CommandStatus_MAX Nfc_CommandStatus_ERROR_BUSY
#define _Nfc_CommandStatus_ARRAYSIZE ((Nfc_CommandStatus)(Nfc_CommandStatus_ERROR_BUSY+1))


#define Nfc_Main_command_status_ENUMTYPE Nfc_CommandStatus


/* Initializer values for message structs */
#define Nfc_Empty_init_default                   {0}
#define Nfc_Main_init_default                    {_Nfc_CommandStatus_MIN, {{NULL}, NULL}, 0, {Nfc_Empty_init_default}}
#define Nfc_Empty_init_zero                      {0}
#define Nfc_Main_init_zero                       {_Nfc_CommandStatus_MIN, {{NULL}, NULL}, 0, {Nfc_Empty_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Nfc_Main_command_status_tag              1
#define Nfc_Main_empty_tag                       2
#define Nfc_Main_nfca_read_req_tag               3
#define Nfc_Main_nfca_read_resp_tag              4
#define Nfc_Main_nfca_emulate_start_req_tag      5
#define Nfc_Main_nfca_emulate_start_resp_tag     6
#define Nfc_Main_nfca_emulate_stop_req_tag       7
#define Nfc_Main_nfca_emulate_stop_resp_tag      8
#define Nfc_Main_mf_ultralight_read_page_req_tag 9
#define Nfc_Main_mf_ultralight_read_page_resp_tag 10
#define Nfc_Main_mf_ultralight_read_version_req_tag 11
#define Nfc_Main_mf_ultralight_read_version_resp_tag 12
#define Nfc_Main_mf_ultralight_write_page_req_tag 13
#define Nfc_Main_mf_ultralight_write_page_resp_tag 14
#define Nfc_Main_mf_ultralight_read_signature_req_tag 15
#define Nfc_Main_mf_ultralight_read_signature_resp_tag 16
#define Nfc_Main_mf_ultralight_read_counter_req_tag 17
#define Nfc_Main_mf_ultralight_read_counter_resp_tag 18
#define Nfc_Main_mf_ultralight_read_tearing_flag_req_tag 19
#define Nfc_Main_mf_ultralight_read_tearing_flag_resp_tag 20
#define Nfc_Main_mf_ultralight_emulate_start_req_tag 21
#define Nfc_Main_mf_ultralight_emulate_start_resp_tag 22
#define Nfc_Main_mf_ultralight_emulate_stop_req_tag 23
#define Nfc_Main_mf_ultralight_emulate_stop_resp_tag 24

/* Struct field encoding specification for nanopb */
#define Nfc_Empty_FIELDLIST(X, a) \

#define Nfc_Empty_CALLBACK NULL
#define Nfc_Empty_DEFAULT NULL

#define Nfc_Main_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command_status,    1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,empty,content.empty),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_read_req,content.nfca_read_req),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_read_resp,content.nfca_read_resp),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_emulate_start_req,content.nfca_emulate_start_req),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_emulate_start_resp,content.nfca_emulate_start_resp),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_emulate_stop_req,content.nfca_emulate_stop_req),   7) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,nfca_emulate_stop_resp,content.nfca_emulate_stop_resp),   8) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_page_req,content.mf_ultralight_read_page_req),   9) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_page_resp,content.mf_ultralight_read_page_resp),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_version_req,content.mf_ultralight_read_version_req),  11) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_version_resp,content.mf_ultralight_read_version_resp),  12) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_write_page_req,content.mf_ultralight_write_page_req),  13) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_write_page_resp,content.mf_ultralight_write_page_resp),  14) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_signature_req,content.mf_ultralight_read_signature_req),  15) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_signature_resp,content.mf_ultralight_read_signature_resp),  16) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_counter_req,content.mf_ultralight_read_counter_req),  17) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_counter_resp,content.mf_ultralight_read_counter_resp),  18) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_tearing_flag_req,content.mf_ultralight_read_tearing_flag_req),  19) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_read_tearing_flag_resp,content.mf_ultralight_read_tearing_flag_resp),  20) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_emulate_start_req,content.mf_ultralight_emulate_start_req),  21) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_emulate_start_resp,content.mf_ultralight_emulate_start_resp),  22) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_emulate_stop_req,content.mf_ultralight_emulate_stop_req),  23) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (content,mf_ultralight_emulate_stop_resp,content.mf_ultralight_emulate_stop_resp),  24)
#define Nfc_Main_CALLBACK NULL
#define Nfc_Main_DEFAULT NULL
#define Nfc_Main_content_empty_MSGTYPE Nfc_Empty
#define Nfc_Main_content_nfca_read_req_MSGTYPE PB_Nfca_ReadRequest
#define Nfc_Main_content_nfca_read_resp_MSGTYPE PB_Nfca_ReadResponse
#define Nfc_Main_content_nfca_emulate_start_req_MSGTYPE PB_Nfca_EmulateStartRequest
#define Nfc_Main_content_nfca_emulate_start_resp_MSGTYPE PB_Nfca_EmulateStartResponse
#define Nfc_Main_content_nfca_emulate_stop_req_MSGTYPE PB_Nfca_EmulateStopRequest
#define Nfc_Main_content_nfca_emulate_stop_resp_MSGTYPE PB_Nfca_EmulateStopResponse
#define Nfc_Main_content_mf_ultralight_read_page_req_MSGTYPE PB_MfUltralight_ReadPageRequest
#define Nfc_Main_content_mf_ultralight_read_page_resp_MSGTYPE PB_MfUltralight_ReadPageResponse
#define Nfc_Main_content_mf_ultralight_read_version_req_MSGTYPE PB_MfUltralight_ReadVersionRequest
#define Nfc_Main_content_mf_ultralight_read_version_resp_MSGTYPE PB_MfUltralight_ReadVersionResponse
#define Nfc_Main_content_mf_ultralight_write_page_req_MSGTYPE PB_MfUltralight_WritePageRequest
#define Nfc_Main_content_mf_ultralight_write_page_resp_MSGTYPE PB_MfUltralight_WritePageResponse
#define Nfc_Main_content_mf_ultralight_read_signature_req_MSGTYPE PB_MfUltralight_ReadSignatureRequest
#define Nfc_Main_content_mf_ultralight_read_signature_resp_MSGTYPE PB_MfUltralight_ReadSignatureResponse
#define Nfc_Main_content_mf_ultralight_read_counter_req_MSGTYPE PB_MfUltralight_ReadCounterRequest
#define Nfc_Main_content_mf_ultralight_read_counter_resp_MSGTYPE PB_MfUltralight_ReadCounterResponse
#define Nfc_Main_content_mf_ultralight_read_tearing_flag_req_MSGTYPE PB_MfUltralight_ReadTearingFlagRequest
#define Nfc_Main_content_mf_ultralight_read_tearing_flag_resp_MSGTYPE PB_MfUltralight_ReadTearingFlagResponse
#define Nfc_Main_content_mf_ultralight_emulate_start_req_MSGTYPE PB_MfUltralight_EmulateStartRequest
#define Nfc_Main_content_mf_ultralight_emulate_start_resp_MSGTYPE PB_MfUltralight_EmulateStartResponse
#define Nfc_Main_content_mf_ultralight_emulate_stop_req_MSGTYPE PB_MfUltralight_EmulationStopRequest
#define Nfc_Main_content_mf_ultralight_emulate_stop_resp_MSGTYPE PB_MfUltralight_EmulationStopResponse

extern const pb_msgdesc_t Nfc_Empty_msg;
extern const pb_msgdesc_t Nfc_Main_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Nfc_Empty_fields &Nfc_Empty_msg
#define Nfc_Main_fields &Nfc_Main_msg

/* Maximum encoded size of messages (where known) */
#define Nfc_Empty_size                           0
#define Nfc_Main_size                            2057

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
