/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_PB_MFCLASSIC_MF_CLASSIC_PB_H_INCLUDED
#define PB_PB_MFCLASSIC_MF_CLASSIC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _PB_MfClassic_Error {
    PB_MfClassic_Error_None = 0,
    PB_MfClassic_Error_NotPresent = 1,
    PB_MfClassic_Error_Protocol = 2,
    PB_MfClassic_Error_Auth = 3,
    PB_MfClassic_Error_Timeout = 4
} PB_MfClassic_Error;

typedef enum _PB_MfClassic_KeyType {
    PB_MfClassic_KeyType_KeyTypeA = 0,
    PB_MfClassic_KeyType_KeyTypeB = 1
} PB_MfClassic_KeyType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_AuthRequest_key_t;
typedef struct _PB_MfClassic_AuthRequest {
    uint8_t block;
    PB_MfClassic_AuthRequest_key_t key;
    PB_MfClassic_KeyType key_type;
} PB_MfClassic_AuthRequest;

typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_AuthResponse_key_t;
typedef PB_BYTES_ARRAY_T(4) PB_MfClassic_AuthResponse_nt_t;
typedef PB_BYTES_ARRAY_T(4) PB_MfClassic_AuthResponse_nr_t;
typedef PB_BYTES_ARRAY_T(4) PB_MfClassic_AuthResponse_ar_t;
typedef PB_BYTES_ARRAY_T(4) PB_MfClassic_AuthResponse_at_t;
typedef struct _PB_MfClassic_AuthResponse {
    PB_MfClassic_Error error;
    uint8_t block;
    PB_MfClassic_AuthResponse_key_t key;
    PB_MfClassic_KeyType key_type;
    PB_MfClassic_AuthResponse_nt_t nt;
    PB_MfClassic_AuthResponse_nr_t nr;
    PB_MfClassic_AuthResponse_ar_t ar;
    PB_MfClassic_AuthResponse_at_t at;
} PB_MfClassic_AuthResponse;

typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_ReadBlockRequest_key_t;
typedef struct _PB_MfClassic_ReadBlockRequest {
    uint8_t block;
    PB_MfClassic_ReadBlockRequest_key_t key;
    PB_MfClassic_KeyType key_type;
} PB_MfClassic_ReadBlockRequest;

typedef PB_BYTES_ARRAY_T(16) PB_MfClassic_ReadBlockResponse_data_t;
typedef struct _PB_MfClassic_ReadBlockResponse {
    PB_MfClassic_Error error;
    PB_MfClassic_ReadBlockResponse_data_t data;
} PB_MfClassic_ReadBlockResponse;

typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_WriteBlockRequest_key_t;
typedef PB_BYTES_ARRAY_T(16) PB_MfClassic_WriteBlockRequest_data_t;
typedef struct _PB_MfClassic_WriteBlockRequest {
    uint8_t block;
    PB_MfClassic_WriteBlockRequest_key_t key;
    PB_MfClassic_KeyType key_type;
    PB_MfClassic_WriteBlockRequest_data_t data;
} PB_MfClassic_WriteBlockRequest;

typedef struct _PB_MfClassic_WriteBlockResponse {
    PB_MfClassic_Error error;
} PB_MfClassic_WriteBlockResponse;

typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_ReadValueRequest_key_t;
typedef struct _PB_MfClassic_ReadValueRequest {
    uint8_t block;
    PB_MfClassic_ReadValueRequest_key_t key;
    PB_MfClassic_KeyType key_type;
} PB_MfClassic_ReadValueRequest;

typedef struct _PB_MfClassic_ReadValueResponse {
    PB_MfClassic_Error error;
    int32_t value;
} PB_MfClassic_ReadValueResponse;

typedef PB_BYTES_ARRAY_T(6) PB_MfClassic_ChangeValueRequest_key_t;
typedef struct _PB_MfClassic_ChangeValueRequest {
    uint8_t block;
    PB_MfClassic_ChangeValueRequest_key_t key;
    PB_MfClassic_KeyType key_type;
    int32_t data;
} PB_MfClassic_ChangeValueRequest;

typedef struct _PB_MfClassic_ChangeValueResponse {
    PB_MfClassic_Error error;
    int32_t value;
} PB_MfClassic_ChangeValueResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PB_MfClassic_Error_MIN PB_MfClassic_Error_None
#define _PB_MfClassic_Error_MAX PB_MfClassic_Error_Timeout
#define _PB_MfClassic_Error_ARRAYSIZE ((PB_MfClassic_Error)(PB_MfClassic_Error_Timeout+1))

#define _PB_MfClassic_KeyType_MIN PB_MfClassic_KeyType_KeyTypeA
#define _PB_MfClassic_KeyType_MAX PB_MfClassic_KeyType_KeyTypeB
#define _PB_MfClassic_KeyType_ARRAYSIZE ((PB_MfClassic_KeyType)(PB_MfClassic_KeyType_KeyTypeB+1))

#define PB_MfClassic_AuthRequest_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_AuthResponse_error_ENUMTYPE PB_MfClassic_Error
#define PB_MfClassic_AuthResponse_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_ReadBlockRequest_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_ReadBlockResponse_error_ENUMTYPE PB_MfClassic_Error

#define PB_MfClassic_WriteBlockRequest_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_WriteBlockResponse_error_ENUMTYPE PB_MfClassic_Error

#define PB_MfClassic_ReadValueRequest_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_ReadValueResponse_error_ENUMTYPE PB_MfClassic_Error

#define PB_MfClassic_ChangeValueRequest_key_type_ENUMTYPE PB_MfClassic_KeyType

#define PB_MfClassic_ChangeValueResponse_error_ENUMTYPE PB_MfClassic_Error


/* Initializer values for message structs */
#define PB_MfClassic_AuthRequest_init_default    {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_AuthResponse_init_default   {_PB_MfClassic_Error_MIN, 0, {0, {0}}, _PB_MfClassic_KeyType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define PB_MfClassic_ReadBlockRequest_init_default {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_ReadBlockResponse_init_default {_PB_MfClassic_Error_MIN, {0, {0}}}
#define PB_MfClassic_WriteBlockRequest_init_default {0, {0, {0}}, _PB_MfClassic_KeyType_MIN, {0, {0}}}
#define PB_MfClassic_WriteBlockResponse_init_default {_PB_MfClassic_Error_MIN}
#define PB_MfClassic_ReadValueRequest_init_default {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_ReadValueResponse_init_default {_PB_MfClassic_Error_MIN, 0}
#define PB_MfClassic_ChangeValueRequest_init_default {0, {0, {0}}, _PB_MfClassic_KeyType_MIN, 0}
#define PB_MfClassic_ChangeValueResponse_init_default {_PB_MfClassic_Error_MIN, 0}
#define PB_MfClassic_AuthRequest_init_zero       {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_AuthResponse_init_zero      {_PB_MfClassic_Error_MIN, 0, {0, {0}}, _PB_MfClassic_KeyType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define PB_MfClassic_ReadBlockRequest_init_zero  {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_ReadBlockResponse_init_zero {_PB_MfClassic_Error_MIN, {0, {0}}}
#define PB_MfClassic_WriteBlockRequest_init_zero {0, {0, {0}}, _PB_MfClassic_KeyType_MIN, {0, {0}}}
#define PB_MfClassic_WriteBlockResponse_init_zero {_PB_MfClassic_Error_MIN}
#define PB_MfClassic_ReadValueRequest_init_zero  {0, {0, {0}}, _PB_MfClassic_KeyType_MIN}
#define PB_MfClassic_ReadValueResponse_init_zero {_PB_MfClassic_Error_MIN, 0}
#define PB_MfClassic_ChangeValueRequest_init_zero {0, {0, {0}}, _PB_MfClassic_KeyType_MIN, 0}
#define PB_MfClassic_ChangeValueResponse_init_zero {_PB_MfClassic_Error_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PB_MfClassic_AuthRequest_block_tag       1
#define PB_MfClassic_AuthRequest_key_tag         2
#define PB_MfClassic_AuthRequest_key_type_tag    3
#define PB_MfClassic_AuthResponse_error_tag      1
#define PB_MfClassic_AuthResponse_block_tag      2
#define PB_MfClassic_AuthResponse_key_tag        3
#define PB_MfClassic_AuthResponse_key_type_tag   4
#define PB_MfClassic_AuthResponse_nt_tag         5
#define PB_MfClassic_AuthResponse_nr_tag         6
#define PB_MfClassic_AuthResponse_ar_tag         7
#define PB_MfClassic_AuthResponse_at_tag         8
#define PB_MfClassic_ReadBlockRequest_block_tag  1
#define PB_MfClassic_ReadBlockRequest_key_tag    2
#define PB_MfClassic_ReadBlockRequest_key_type_tag 3
#define PB_MfClassic_ReadBlockResponse_error_tag 1
#define PB_MfClassic_ReadBlockResponse_data_tag  2
#define PB_MfClassic_WriteBlockRequest_block_tag 1
#define PB_MfClassic_WriteBlockRequest_key_tag   2
#define PB_MfClassic_WriteBlockRequest_key_type_tag 3
#define PB_MfClassic_WriteBlockRequest_data_tag  4
#define PB_MfClassic_WriteBlockResponse_error_tag 1
#define PB_MfClassic_ReadValueRequest_block_tag  1
#define PB_MfClassic_ReadValueRequest_key_tag    2
#define PB_MfClassic_ReadValueRequest_key_type_tag 3
#define PB_MfClassic_ReadValueResponse_error_tag 1
#define PB_MfClassic_ReadValueResponse_value_tag 2
#define PB_MfClassic_ChangeValueRequest_block_tag 1
#define PB_MfClassic_ChangeValueRequest_key_tag  2
#define PB_MfClassic_ChangeValueRequest_key_type_tag 3
#define PB_MfClassic_ChangeValueRequest_data_tag 4
#define PB_MfClassic_ChangeValueResponse_error_tag 1
#define PB_MfClassic_ChangeValueResponse_value_tag 2

/* Struct field encoding specification for nanopb */
#define PB_MfClassic_AuthRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   block,             1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          3)
#define PB_MfClassic_AuthRequest_CALLBACK NULL
#define PB_MfClassic_AuthRequest_DEFAULT NULL

#define PB_MfClassic_AuthResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, UINT32,   block,             2) \
X(a, STATIC,   SINGULAR, BYTES,    key,               3) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          4) \
X(a, STATIC,   SINGULAR, BYTES,    nt,                5) \
X(a, STATIC,   SINGULAR, BYTES,    nr,                6) \
X(a, STATIC,   SINGULAR, BYTES,    ar,                7) \
X(a, STATIC,   SINGULAR, BYTES,    at,                8)
#define PB_MfClassic_AuthResponse_CALLBACK NULL
#define PB_MfClassic_AuthResponse_DEFAULT NULL

#define PB_MfClassic_ReadBlockRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   block,             1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          3)
#define PB_MfClassic_ReadBlockRequest_CALLBACK NULL
#define PB_MfClassic_ReadBlockRequest_DEFAULT NULL

#define PB_MfClassic_ReadBlockResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define PB_MfClassic_ReadBlockResponse_CALLBACK NULL
#define PB_MfClassic_ReadBlockResponse_DEFAULT NULL

#define PB_MfClassic_WriteBlockRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   block,             1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          3) \
X(a, STATIC,   SINGULAR, BYTES,    data,              4)
#define PB_MfClassic_WriteBlockRequest_CALLBACK NULL
#define PB_MfClassic_WriteBlockRequest_DEFAULT NULL

#define PB_MfClassic_WriteBlockResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define PB_MfClassic_WriteBlockResponse_CALLBACK NULL
#define PB_MfClassic_WriteBlockResponse_DEFAULT NULL

#define PB_MfClassic_ReadValueRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   block,             1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          3)
#define PB_MfClassic_ReadValueRequest_CALLBACK NULL
#define PB_MfClassic_ReadValueRequest_DEFAULT NULL

#define PB_MfClassic_ReadValueResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define PB_MfClassic_ReadValueResponse_CALLBACK NULL
#define PB_MfClassic_ReadValueResponse_DEFAULT NULL

#define PB_MfClassic_ChangeValueRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   block,             1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          3) \
X(a, STATIC,   SINGULAR, INT32,    data,              4)
#define PB_MfClassic_ChangeValueRequest_CALLBACK NULL
#define PB_MfClassic_ChangeValueRequest_DEFAULT NULL

#define PB_MfClassic_ChangeValueResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define PB_MfClassic_ChangeValueResponse_CALLBACK NULL
#define PB_MfClassic_ChangeValueResponse_DEFAULT NULL

extern const pb_msgdesc_t PB_MfClassic_AuthRequest_msg;
extern const pb_msgdesc_t PB_MfClassic_AuthResponse_msg;
extern const pb_msgdesc_t PB_MfClassic_ReadBlockRequest_msg;
extern const pb_msgdesc_t PB_MfClassic_ReadBlockResponse_msg;
extern const pb_msgdesc_t PB_MfClassic_WriteBlockRequest_msg;
extern const pb_msgdesc_t PB_MfClassic_WriteBlockResponse_msg;
extern const pb_msgdesc_t PB_MfClassic_ReadValueRequest_msg;
extern const pb_msgdesc_t PB_MfClassic_ReadValueResponse_msg;
extern const pb_msgdesc_t PB_MfClassic_ChangeValueRequest_msg;
extern const pb_msgdesc_t PB_MfClassic_ChangeValueResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PB_MfClassic_AuthRequest_fields &PB_MfClassic_AuthRequest_msg
#define PB_MfClassic_AuthResponse_fields &PB_MfClassic_AuthResponse_msg
#define PB_MfClassic_ReadBlockRequest_fields &PB_MfClassic_ReadBlockRequest_msg
#define PB_MfClassic_ReadBlockResponse_fields &PB_MfClassic_ReadBlockResponse_msg
#define PB_MfClassic_WriteBlockRequest_fields &PB_MfClassic_WriteBlockRequest_msg
#define PB_MfClassic_WriteBlockResponse_fields &PB_MfClassic_WriteBlockResponse_msg
#define PB_MfClassic_ReadValueRequest_fields &PB_MfClassic_ReadValueRequest_msg
#define PB_MfClassic_ReadValueResponse_fields &PB_MfClassic_ReadValueResponse_msg
#define PB_MfClassic_ChangeValueRequest_fields &PB_MfClassic_ChangeValueRequest_msg
#define PB_MfClassic_ChangeValueResponse_fields &PB_MfClassic_ChangeValueResponse_msg

/* Maximum encoded size of messages (where known) */
#define PB_MfClassic_AuthRequest_size            13
#define PB_MfClassic_AuthResponse_size           39
#define PB_MfClassic_ChangeValueRequest_size     24
#define PB_MfClassic_ChangeValueResponse_size    13
#define PB_MfClassic_ReadBlockRequest_size       13
#define PB_MfClassic_ReadBlockResponse_size      20
#define PB_MfClassic_ReadValueRequest_size       13
#define PB_MfClassic_ReadValueResponse_size      13
#define PB_MfClassic_WriteBlockRequest_size      31
#define PB_MfClassic_WriteBlockResponse_size     2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
