/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "mf_ultralight.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_MfUltralight_ReadPageRequest, PB_MfUltralight_ReadPageRequest, AUTO)


PB_BIND(PB_MfUltralight_ReadPageResponse, PB_MfUltralight_ReadPageResponse, AUTO)


PB_BIND(PB_MfUltralight_ReadVersionRequest, PB_MfUltralight_ReadVersionRequest, AUTO)


PB_BIND(PB_MfUltralight_ReadVersionResponse, PB_MfUltralight_ReadVersionResponse, AUTO)


PB_BIND(PB_MfUltralight_WritePageRequest, PB_MfUltralight_WritePageRequest, AUTO)


PB_BIND(PB_MfUltralight_WritePageResponse, PB_MfUltralight_WritePageResponse, AUTO)


PB_BIND(PB_MfUltralight_ReadSignatureRequest, PB_MfUltralight_ReadSignatureRequest, AUTO)


PB_BIND(PB_MfUltralight_ReadSignatureResponse, PB_MfUltralight_ReadSignatureResponse, AUTO)


PB_BIND(PB_MfUltralight_ReadCounterRequest, PB_MfUltralight_ReadCounterRequest, AUTO)


PB_BIND(PB_MfUltralight_ReadCounterResponse, PB_MfUltralight_ReadCounterResponse, AUTO)


PB_BIND(PB_MfUltralight_ReadTearingFlagRequest, PB_MfUltralight_ReadTearingFlagRequest, AUTO)


PB_BIND(PB_MfUltralight_ReadTearingFlagResponse, PB_MfUltralight_ReadTearingFlagResponse, AUTO)


PB_BIND(PB_MfUltralight_EmulateStartRequest, PB_MfUltralight_EmulateStartRequest, 2)


PB_BIND(PB_MfUltralight_EmulateStartResponse, PB_MfUltralight_EmulateStartResponse, AUTO)


PB_BIND(PB_MfUltralight_EmulationStopRequest, PB_MfUltralight_EmulationStopRequest, AUTO)


PB_BIND(PB_MfUltralight_EmulationStopResponse, PB_MfUltralight_EmulationStopResponse, AUTO)




