/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "nfca.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_Nfca_ReadRequest, PB_Nfca_ReadRequest, AUTO)

PB_BIND(PB_Nfca_ReadResponse, PB_Nfca_ReadResponse, AUTO)

PB_BIND(PB_Nfca_EmulateStartRequest, PB_Nfca_EmulateStartRequest, AUTO)

PB_BIND(PB_Nfca_EmulateStartResponse, PB_Nfca_EmulateStartResponse, AUTO)

PB_BIND(PB_Nfca_EmulateStopRequest, PB_Nfca_EmulateStopRequest, AUTO)

PB_BIND(PB_Nfca_EmulateStopResponse, PB_Nfca_EmulateStopResponse, AUTO)
