Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/subghz",
    ],
)

libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("subghz", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
