Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/subghz",
    ],
    CPPDEFINES=[],
)

libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c*", ".")

lib = libenv.StaticLibrary("subghz", sources)
libenv.Install("#/${BUILD_DIR}/lib", lib)
Return("lib")
