Import("env", "lib_flags")

env.Append(
    CPPPATH=[
        "#/lib/ST25RFAL002",
        "#/lib/ST25RFAL002/include",
        "#/lib/ST25RFAL002/source/st25r3916",
    ],
)


libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("st25rfal002", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
