/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_Payload_H_
#define	_Payload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SamCommand.h"
#include "NFCCommand.h"
#include "Response.h"
#include "ErrorResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Payload_PR {
	Payload_PR_NOTHING,	/* No components present */
	Payload_PR_samCommand,
	Payload_PR_nfcCommand,
	Payload_PR_response,
	Payload_PR_errorResponse
} Payload_PR;

/* Payload */
typedef struct Payload {
	Payload_PR present;
	union Payload_u {
		SamCommand_t	 samCommand;
		NFCCommand_t	 nfcCommand;
		Response_t	 response;
		ErrorResponse_t	 errorResponse;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Payload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Payload;

#ifdef __cplusplus
}
#endif

#endif	/* _Payload_H_ */
#include <asn_internal.h>
