import { build } from "esbuild";

build({
    entryPoints: ["dist/index.js"],
    outfile: "dist/index.min.js",
    tsconfig: "tsconfig.json",
    format: "cjs",
    bundle: true,
    minify: true,
    external: [
        "@flipperdevices/fz-sdk/*"
    ],
    supported: {
        "array-spread": false,
        "arrow": false,
        "async-await": false,
        "async-generator": false,
        "bigint": false,
        "class": false,
        "const-and-let": true,
        "decorators": false,
        "default-argument": false,
        "destructuring": false,
        "dynamic-import": false,
        "exponent-operator": false,
        "export-star-as": false,
        "for-await": false,
        "for-of": false,
        "function-name-configurable": false,
        "function-or-class-property-access": false,
        "generator": false,
        "hashbang": false,
        "import-assertions": false,
        "import-meta": false,
        "inline-script": false,
        "logical-assignment": false,
        "nested-rest-binding": false,
        "new-target": false,
        "node-colon-prefix-import": false,
        "node-colon-prefix-require": false,
        "nullish-coalescing": false,
        "object-accessors": false,
        "object-extensions": false,
        "object-rest-spread": false,
        "optional-catch-binding": false,
        "optional-chain": false,
        "regexp-dot-all-flag": false,
        "regexp-lookbehind-assertions": false,
        "regexp-match-indices": false,
        "regexp-named-capture-groups": false,
        "regexp-set-notation": false,
        "regexp-sticky-and-unicode-flags": false,
        "regexp-unicode-property-escapes": false,
        "rest-argument": false,
        "template-literal": false,
        "top-level-await": false,
        "typeof-exotic-object-is-object": false,
        "unicode-escapes": false,
        "using": false,
    },
});
