Import("env")

env.Append(
    CPPPATH=[
        "#/lib/pure",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("bit_lib.h"),
        File("float_tools.h"),
        File("hex.h"),
        File("strint.h"),
        File("value_index.h"),
        File("varint.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="pure")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
