ADD_SCENE(mass_storage, start, Start)
ADD_SCENE(mass_storage, file_select, FileSelect)
ADD_SCENE(mass_storage, work, Work)
ADD_SCENE(mass_storage, file_name, FileName)
ADD_SCENE(mass_storage, usb_locked, UsbLocked)
