ADD_SCENE(meal_pager, startscreen, Startscreen)
ADD_SCENE(meal_pager, menu, Menu)
ADD_SCENE(meal_pager, transmit, Transmit)
ADD_SCENE(meal_pager, settings, Settings)
ADD_SCENE(meal_pager, set_first_station, SetFirstStation)
ADD_SCENE(meal_pager, set_last_station, SetLastStation)
ADD_SCENE(meal_pager, set_first_pager, SetFirstPager)
ADD_SCENE(meal_pager, set_last_pager, SetLastPager)