ADD_SCENE(xremote, infoscreen, Infoscreen)
ADD_SCENE(xremote, menu, Menu)
ADD_SCENE(xremote, create, Create)
ADD_SCENE(xremote, create_add, CreateAdd)
ADD_SCENE(xremote, scene_2, Scene_2)
ADD_SCENE(xremote, settings, Settings)
ADD_SCENE(xremote, wip, Wip)