/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "animation_storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_FA_Bubble, PB_FA_Bubble, AUTO)


PB_BIND(PB_FA_AnimationBubble, PB_FA_AnimationBubble, AUTO)


PB_BIND(PB_FA_AnimationFrame, PB_FA_AnimationFrame, AUTO)


PB_BIND(PB_FA_StorageAnimationFile, PB_FA_StorageAnimationFile, AUTO)


PB_BIND(PB_FA_StorageAnimationMetaFile, PB_FA_StorageAnimationMetaFile, AUTO)


PB_BIND(PB_FA_StorageAnimationMeta, PB_FA_StorageAnimationMeta, AUTO)




