/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_Storage_Element, PB_Storage_Element, AUTO)


PB_BIND(PB_Storage_ListRequest, PB_Storage_ListRequest, AUTO)


PB_BIND(PB_Storage_ListResponse, PB_Storage_ListResponse, 2)


PB_BIND(PB_Storage_ReadRequest, PB_Storage_ReadRequest, AUTO)


PB_BIND(PB_Storage_ReadResponse, PB_Storage_ReadResponse, AUTO)


PB_BIND(PB_Storage_WriteRequest, PB_Storage_WriteRequest, AUTO)


PB_BIND(PB_Storage_DeleteRequest, PB_Storage_DeleteRequest, AUTO)




