/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_STORAGE_STORAGE_PB_H_INCLUDED
#define PB_STORAGE_STORAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Storage_Element_FileType { 
    Storage_Element_FileType_FILE = 0, 
    Storage_Element_FileType_DIR = 1 
} Storage_Element_FileType;

/* Struct definitions */
typedef struct _Storage_DeleteRequest { 
    pb_callback_t filename; 
} Storage_DeleteRequest;

typedef struct _Storage_ListRequest { 
    pb_callback_t path; 
} Storage_ListRequest;

typedef struct _Storage_ListResponse { 
    pb_callback_t storage_element; 
} Storage_ListResponse;

typedef struct _Storage_ReadRequest { 
    pb_callback_t filepath; 
} Storage_ReadRequest;

typedef struct _Storage_Element { 
    Storage_Element_FileType type; 
    pb_callback_t name; 
    uint64_t size; 
    pb_callback_t data; 
} Storage_Element;

typedef struct _Storage_ReadResponse { 
    bool has_storage_element;
    Storage_Element storage_element; 
} Storage_ReadResponse;

typedef struct _Storage_WriteRequest { 
    pb_callback_t path; 
    bool has_storage_element;
    Storage_Element storage_element; 
} Storage_WriteRequest;


/* Helper constants for enums */
#define _Storage_Element_FileType_MIN Storage_Element_FileType_FILE
#define _Storage_Element_FileType_MAX Storage_Element_FileType_DIR
#define _Storage_Element_FileType_ARRAYSIZE ((Storage_Element_FileType)(Storage_Element_FileType_DIR+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Storage_Element_init_default             {_Storage_Element_FileType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Storage_ListRequest_init_default         {{{NULL}, NULL}}
#define Storage_ListResponse_init_default        {{{NULL}, NULL}}
#define Storage_ReadRequest_init_default         {{{NULL}, NULL}}
#define Storage_ReadResponse_init_default        {false, Storage_Element_init_default}
#define Storage_WriteRequest_init_default        {{{NULL}, NULL}, false, Storage_Element_init_default}
#define Storage_DeleteRequest_init_default       {{{NULL}, NULL}}
#define Storage_Element_init_zero                {_Storage_Element_FileType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Storage_ListRequest_init_zero            {{{NULL}, NULL}}
#define Storage_ListResponse_init_zero           {{{NULL}, NULL}}
#define Storage_ReadRequest_init_zero            {{{NULL}, NULL}}
#define Storage_ReadResponse_init_zero           {false, Storage_Element_init_zero}
#define Storage_WriteRequest_init_zero           {{{NULL}, NULL}, false, Storage_Element_init_zero}
#define Storage_DeleteRequest_init_zero          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Storage_DeleteRequest_filename_tag       1
#define Storage_ListRequest_path_tag             1
#define Storage_ListResponse_storage_element_tag 1
#define Storage_ReadRequest_filepath_tag         1
#define Storage_Element_type_tag                 1
#define Storage_Element_name_tag                 2
#define Storage_Element_size_tag                 3
#define Storage_Element_data_tag                 4
#define Storage_ReadResponse_storage_element_tag 1
#define Storage_WriteRequest_path_tag            1
#define Storage_WriteRequest_storage_element_tag 2

/* Struct field encoding specification for nanopb */
#define Storage_Element_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT64,   size,              3) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              4)
#define Storage_Element_CALLBACK pb_default_field_callback
#define Storage_Element_DEFAULT NULL

#define Storage_ListRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1)
#define Storage_ListRequest_CALLBACK pb_default_field_callback
#define Storage_ListRequest_DEFAULT NULL

#define Storage_ListResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  storage_element,   1)
#define Storage_ListResponse_CALLBACK pb_default_field_callback
#define Storage_ListResponse_DEFAULT NULL
#define Storage_ListResponse_storage_element_MSGTYPE Storage_Element

#define Storage_ReadRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   filepath,          1)
#define Storage_ReadRequest_CALLBACK pb_default_field_callback
#define Storage_ReadRequest_DEFAULT NULL

#define Storage_ReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  storage_element,   1)
#define Storage_ReadResponse_CALLBACK NULL
#define Storage_ReadResponse_DEFAULT NULL
#define Storage_ReadResponse_storage_element_MSGTYPE Storage_Element

#define Storage_WriteRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  storage_element,   2)
#define Storage_WriteRequest_CALLBACK pb_default_field_callback
#define Storage_WriteRequest_DEFAULT NULL
#define Storage_WriteRequest_storage_element_MSGTYPE Storage_Element

#define Storage_DeleteRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   filename,          1)
#define Storage_DeleteRequest_CALLBACK pb_default_field_callback
#define Storage_DeleteRequest_DEFAULT NULL

extern const pb_msgdesc_t Storage_Element_msg;
extern const pb_msgdesc_t Storage_ListRequest_msg;
extern const pb_msgdesc_t Storage_ListResponse_msg;
extern const pb_msgdesc_t Storage_ReadRequest_msg;
extern const pb_msgdesc_t Storage_ReadResponse_msg;
extern const pb_msgdesc_t Storage_WriteRequest_msg;
extern const pb_msgdesc_t Storage_DeleteRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Storage_Element_fields &Storage_Element_msg
#define Storage_ListRequest_fields &Storage_ListRequest_msg
#define Storage_ListResponse_fields &Storage_ListResponse_msg
#define Storage_ReadRequest_fields &Storage_ReadRequest_msg
#define Storage_ReadResponse_fields &Storage_ReadResponse_msg
#define Storage_WriteRequest_fields &Storage_WriteRequest_msg
#define Storage_DeleteRequest_fields &Storage_DeleteRequest_msg

/* Maximum encoded size of messages (where known) */
/* Storage_Element_size depends on runtime parameters */
/* Storage_ListRequest_size depends on runtime parameters */
/* Storage_ListResponse_size depends on runtime parameters */
/* Storage_ReadRequest_size depends on runtime parameters */
/* Storage_ReadResponse_size depends on runtime parameters */
/* Storage_WriteRequest_size depends on runtime parameters */
/* Storage_DeleteRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
