/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Storage_Element, Storage_Element, AUTO)


PB_BIND(Storage_ListRequest, Storage_ListRequest, AUTO)


PB_BIND(Storage_ListResponse, Storage_ListResponse, AUTO)


PB_BIND(Storage_ReadRequest, Storage_ReadRequest, AUTO)


PB_BIND(Storage_ReadResponse, Storage_ReadResponse, AUTO)


PB_BIND(Storage_WriteRequest, Storage_WriteRequest, AUTO)


PB_BIND(Storage_DeleteRequest, Storage_DeleteRequest, AUTO)




