/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StorageListRequest, StorageListRequest, AUTO)


PB_BIND(StorageListAnswer, StorageListAnswer, AUTO)


PB_BIND(StorageListEOF, StorageListEOF, AUTO)




