Import("env")

env.Append(
    CPPPATH=[
        "#/lib/signal_reader",
    ],
    SDK_HEADERS=[
        File("signal_reader.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="signal_reader")
libenv.ApplyLibFlags()

libenv.AppendUnique(
    CCFLAGS=[
        # Required for lib to be linkable with .faps
        # "-mword-relocations",
        # "-mlong-calls",
    ],
)

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
