#include <stdint.h>

#include "gui.h"
#include "matagotchi_icons.h" // Autogenerated header file

void refresh_gui(ViewPort *view_port) {
    // This call will asynchronously (and in a separated thread)
    // call main_draw_callback()
    view_port_update(view_port);
}

void decode_and_draw_image(Canvas *canvas, struct GameState *game_state) {
    uint32_t next_index = game_state->next_animation_index;

    switch(game_state->persistent.stage) {
        case EGG:
            if(next_index % 2) {
                canvas_draw_icon(canvas, 0, 2, &I_egg_01_60x60);
            } else {
                canvas_draw_icon(canvas, 0, 2, &I_egg_00_60x60);
            }
            break;
        case BABY:
            if(next_index % 6 == 0) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_00_60x60);
            } else if(next_index % 6 == 1) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_01_60x60);
            } else if(next_index % 6 == 2) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_02_60x60);
            } else if(next_index % 6 == 3) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_03_60x60);
            } else if(next_index % 6 == 4) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_04_60x60);
            } else if(next_index % 6 == 5) {
                canvas_draw_icon(canvas, 0, 2, &I_baby_05_60x60);
            }
            break;
        case CHILD:
            if(next_index % 2) {
                canvas_draw_icon(canvas, 0, 2, &I_child_01_60x60);
            } else {
                canvas_draw_icon(canvas, 0, 2, &I_child_00_60x60);
            }
            break;
        case TEEN:
            if(next_index % 2) {
                canvas_draw_icon(canvas, 0, 2, &I_teen_01_60x60);
            } else {
                canvas_draw_icon(canvas, 0, 2, &I_teen_00_60x60);
            }
            break;
        case ADULT:
            if(next_index % 2) {
                canvas_draw_icon(canvas, 0, 2, &I_adult_01_60x60);
            } else {
                canvas_draw_icon(canvas, 0, 2, &I_adult_00_60x60);
            }
            break;
        case DEAD:
            canvas_draw_icon(canvas, 0, 2, &I_dead_00_60x60);
            break;
        default:
            return;
    }
}
