#include <stdint.h>

#include "gui.h"
#include "matagotchi_icons.h" // Autogenerated header file

void init_gui(ViewPort *view_port, struct GameState *game_state) {
    game_state->next_animation_index = 0;
    game_state->animation = EGG;

    // This call will asynchronously (and in a separated thread)
    // call main_draw_callback()
    view_port_update(view_port);
}

void decode_and_draw_image(Canvas *canvas, struct GameState *game_state) {
    uint32_t next_index = game_state->next_animation_index;

    switch(game_state->animation) {
        case EGG:
            if(next_index % 2) {
                canvas_draw_icon(canvas, 0, 2, &I_egg_01_60x60);
            } else {
                canvas_draw_icon(canvas, 0, 2, &I_egg_00_60x60);
            }
            break;
        case INVALID:
        default:
            return;
    }
}
