#include <gui/modules/menu.h>

/* generated by fbt from .png files in images folder */
#include <tone_gen_icons.h>

#include "app_context.h"
#include "tone_gen.h"

#include "menus/main_menu.h"

/** collection of all scene on_enter handlers - in the same order as their enum */
void (*const scene_on_enter_handlers[])(void*) = {
    scene_on_enter_main_menu,
};

/** collection of all scene on event handlers - in the same order as their enum */
bool (*const scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    scene_on_event_main_menu,
};

/** collection of all scene on exit handlers - in the same order as their enum */
void (*const scene_on_exit_handlers[])(void*) = {
    scene_on_exit_main_menu,
};

const SceneManagerHandlers scene_event_handlers = {
    .on_enter_handlers = scene_on_enter_handlers,
    .on_event_handlers = scene_on_event_handlers,
    .on_exit_handlers = scene_on_exit_handlers,
    .scene_num = ToneGenAppScene_count};

int32_t tone_gen_app(void* p) {
    UNUSED(p);

    FURI_LOG_I(TAG, "Tone gen app starting...");

    struct AppContext_t* appContext;
    AppContextStatus result = initializeAppContext(&appContext, &scene_event_handlers);

    if(result == APP_CONTEXT_OK) {
        // set the scene and launch the main loop
        FURI_LOG_D(TAG, "Setting the scene");
        Gui* gui = furi_record_open(RECORD_GUI);
        view_dispatcher_attach_to_gui(
            appContext->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
        scene_manager_next_scene(appContext->scene_manager, ToneGenAppScene_MainMenu);
        FURI_LOG_D(TAG, "Starting the view dispatcher");
        view_dispatcher_run(appContext->view_dispatcher);

        // free all memory
        FURI_LOG_D(TAG, "Ending the app");
        furi_record_close(RECORD_GUI);
        freeAppContext(&appContext);
        return 0;
    }
    return -1;
}
