SET(uGFX_gdisp_SEARCH_PATH ${uGFX_DIR}/src/gdisp)
SET(uGFX_gdisp_HEADERS gdisp_colors.h gdisp_options.h gdisp_rules.h)
SET(uGFX_gdisp_SOURCES gdisp.c)

FOREACH(driver ${uGFX_GDISP_DRIVERS})
    LIST(FIND uGFX_FIND_COMPONENTS ${driver} DRIVER_INDEX)
    IF(NOT ${DRIVER_INDEX} LESS 0)
        SET(uGFX_${driver}_SEARCH_PATH ${uGFX_DIR}/drivers/gdisp/${driver})
        SET(uGFX_${driver}_SOURCES gdisp_lld_${driver}.c)
        SET(uGFX_${driver}_HEADERS gdisp_lld_config.h)
        LIST(APPEND uGFX_GDISP_MODULES ${driver})
    ENDIF()
ENDFOREACH()
