Import("env", "lib_flags")


libenv = env.Clone()
libenv.MergeFlags(lib_flags)

sources = Glob("*.c", source=True)
sources += ["option/unicode.c"]

lib = libenv.StaticLibrary("fatfs", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
