Import("env")

env.Append(
    CPPPATH=[
        "#/lib/digital_signal",
    ],
    SDK_HEADERS=[
        File("digital_signal.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="digital_signal")
libenv.ApplyLibFlags()
libenv.Append(CCFLAGS=["-O3","-unroll-loops","-Ofast"])

libenv.AppendUnique(
    CCFLAGS=[
        # Required for lib to be linkable with .faps
        "-mword-relocations",
        "-mlong-calls",
    ],
)

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
