Import("env", "lib_flags")

libenv = env.Clone()
libenv.MergeFlags(lib_flags)

libenv.Append(
    CPPPATH=[
        "#/assets/compiled",
    ],
)

sources = ["targets/f${TARGET_HW}/startup_stm32wb55xx_cm4.s"]
sources += libenv.GlobRecursive("*.c")

lib = libenv.Library("flipper${TARGET_HW}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
