/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "desktop.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_Desktop_IsLockedRequest, PB_Desktop_IsLockedRequest, AUTO)


PB_BIND(PB_Desktop_UnlockRequest, PB_Desktop_UnlockRequest, AUTO)


PB_BIND(PB_Desktop_StatusSubscribeRequest, PB_Desktop_StatusSubscribeRequest, AUTO)


PB_BIND(PB_Desktop_StatusUnsubscribeRequest, PB_Desktop_StatusUnsubscribeRequest, AUTO)


PB_BIND(PB_Desktop_Status, PB_Desktop_Status, AUTO)



