/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PB_DESKTOP_FLIPPERZERO_PROTOBUF_DESKTOP_PB_H_INCLUDED
#define PB_PB_DESKTOP_FLIPPERZERO_PROTOBUF_DESKTOP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PB_Desktop_IsLockedRequest {
    char dummy_field;
} PB_Desktop_IsLockedRequest;

typedef struct _PB_Desktop_UnlockRequest {
    char dummy_field;
} PB_Desktop_UnlockRequest;

typedef struct _PB_Desktop_StatusSubscribeRequest {
    char dummy_field;
} PB_Desktop_StatusSubscribeRequest;

typedef struct _PB_Desktop_StatusUnsubscribeRequest {
    char dummy_field;
} PB_Desktop_StatusUnsubscribeRequest;

typedef struct _PB_Desktop_Status {
    bool locked;
} PB_Desktop_Status;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PB_Desktop_IsLockedRequest_init_default  {0}
#define PB_Desktop_UnlockRequest_init_default    {0}
#define PB_Desktop_StatusSubscribeRequest_init_default {0}
#define PB_Desktop_StatusUnsubscribeRequest_init_default {0}
#define PB_Desktop_Status_init_default           {0}
#define PB_Desktop_IsLockedRequest_init_zero     {0}
#define PB_Desktop_UnlockRequest_init_zero       {0}
#define PB_Desktop_StatusSubscribeRequest_init_zero {0}
#define PB_Desktop_StatusUnsubscribeRequest_init_zero {0}
#define PB_Desktop_Status_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define PB_Desktop_Status_locked_tag             1

/* Struct field encoding specification for nanopb */
#define PB_Desktop_IsLockedRequest_FIELDLIST(X, a) \

#define PB_Desktop_IsLockedRequest_CALLBACK NULL
#define PB_Desktop_IsLockedRequest_DEFAULT NULL

#define PB_Desktop_UnlockRequest_FIELDLIST(X, a) \

#define PB_Desktop_UnlockRequest_CALLBACK NULL
#define PB_Desktop_UnlockRequest_DEFAULT NULL

#define PB_Desktop_StatusSubscribeRequest_FIELDLIST(X, a) \

#define PB_Desktop_StatusSubscribeRequest_CALLBACK NULL
#define PB_Desktop_StatusSubscribeRequest_DEFAULT NULL

#define PB_Desktop_StatusUnsubscribeRequest_FIELDLIST(X, a) \

#define PB_Desktop_StatusUnsubscribeRequest_CALLBACK NULL
#define PB_Desktop_StatusUnsubscribeRequest_DEFAULT NULL

#define PB_Desktop_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     locked,            1)
#define PB_Desktop_Status_CALLBACK NULL
#define PB_Desktop_Status_DEFAULT NULL

extern const pb_msgdesc_t PB_Desktop_IsLockedRequest_msg;
extern const pb_msgdesc_t PB_Desktop_UnlockRequest_msg;
extern const pb_msgdesc_t PB_Desktop_StatusSubscribeRequest_msg;
extern const pb_msgdesc_t PB_Desktop_StatusUnsubscribeRequest_msg;
extern const pb_msgdesc_t PB_Desktop_Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PB_Desktop_IsLockedRequest_fields &PB_Desktop_IsLockedRequest_msg
#define PB_Desktop_UnlockRequest_fields &PB_Desktop_UnlockRequest_msg
#define PB_Desktop_StatusSubscribeRequest_fields &PB_Desktop_StatusSubscribeRequest_msg
#define PB_Desktop_StatusUnsubscribeRequest_fields &PB_Desktop_StatusUnsubscribeRequest_msg
#define PB_Desktop_Status_fields &PB_Desktop_Status_msg

/* Maximum encoded size of messages (where known) */
#define PB_DESKTOP_FLIPPERZERO_PROTOBUF_DESKTOP_PB_H_MAX_SIZE PB_Desktop_Status_size
#define PB_Desktop_IsLockedRequest_size          0
#define PB_Desktop_StatusSubscribeRequest_size   0
#define PB_Desktop_StatusUnsubscribeRequest_size 0
#define PB_Desktop_Status_size                   2
#define PB_Desktop_UnlockRequest_size            0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
